### ISSUE TITLE
Unable to  Run the script on Mac Python3

### ISSUE THREAD

**Issue by jve2kor** [moinudeen/digit-recognizer-flask-cnn#4]
Syed,

could you help me out in understanding the issue?
I am using python3

` TensorFlow backend.
/Users/venkateshwarreddyjambula/anaconda/envs/aind-dog/lib/python3.5/site-packages/keras/legacy/interfaces.py:86: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(padding="valid", batch_input_shape=[None, 28,..., kernel_regularizer=None, trainable=True, name="convolution2d_1", input_dtype="float32", use_bias=True, strides=[1, 1], data_format="channels_last", kernel_initializer="glorot_uniform", bias_regularizer=None, kernel_constraint=None, kernel_size=(3, 3), bias_constraint=None, activation="linear", filters=32, activity_regularizer=None)`
  '` call to the Keras 2 API: ' + signature)
Traceback (most recent call last):
  File "app.py", line 32, in <module>
    model, graph = init()
  File "/Users/venkateshwarreddyjambula/Documents/Udacity/capstone/how_to_deploy_a_keras_model_to_production-master/model/load.py", line 12, in init
    loaded_model = model_from_json(loaded_model_json)
  File "/Users/venkateshwarreddyjambula/anaconda/envs/aind-dog/lib/python3.5/site-packages/keras/models.py", line 325, in model_from_json
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/Users/venkateshwarreddyjambula/anaconda/envs/aind-dog/lib/python3.5/site-packages/keras/layers/__init__.py", line 46, in deserialize
    printable_module_name='layer')
  File "/Users/venkateshwarreddyjambula/anaconda/envs/aind-dog/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 141, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/Users/venkateshwarreddyjambula/anaconda/envs/aind-dog/lib/python3.5/site-packages/keras/models.py", line 1186, in from_config
    layer = layer_module.deserialize(conf)
  File "/Users/venkateshwarreddyjambula/anaconda/envs/aind-dog/lib/python3.5/site-packages/keras/layers/__init__.py", line 46, in deserialize
    printable_module_name='layer')
  File "/Users/venkateshwarreddyjambula/anaconda/envs/aind-dog/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 141, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/Users/venkateshwarreddyjambula/anaconda/envs/aind-dog/lib/python3.5/site-packages/keras/engine/topology.py", line 1193, in from_config
    return cls(**config)
  File "/Users/venkateshwarreddyjambula/anaconda/envs/aind-dog/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/Users/venkateshwarreddyjambula/anaconda/envs/aind-dog/lib/python3.5/site-packages/keras/layers/convolutional.py", line 455, in __init__
    **kwargs)
  File "/Users/venkateshwarreddyjambula/anaconda/envs/aind-dog/lib/python3.5/site-packages/keras/layers/convolutional.py", line 100, in __init__
    super(_Conv, self).__init__(**kwargs)
  File "/Users/venkateshwarreddyjambula/anaconda/envs/aind-dog/lib/python3.5/site-packages/keras/engine/topology.py", line 275, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'input_dtype')
(aind-dog) Venkateshwar-Reddy-Jambulas-MacBook-Air:how_to_deploy_a_keras_model_to_production-master venkateshwarreddyjambula$ 
`

**Comment by moinudeen** [comment]
Hey @jve2kor , 
I think this error must be popping up due to API changes in Keras' latest version. I used python2 and Keras v1.2 to write this. But you seem to be using Keras v2.0. Keras has seen a lot of changes since v1.2 and the model_from_json function used in v1.2 doesn't seem to work with v2.0. Have a look at this [thread](https://github.com/fchollet/keras/issues/5790).
